ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\syamp\AppData\Roaming
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=SYAMSAIREDDY
ComSpec=C:\WINDOWS\system32\cmd.exe
DriverData=C:\Windows\System32\Drivers\DriverData
HOMEDRIVE=C:
HOMEPATH=\Users\syamp
LOCALAPPDATA=C:\Users\syamp\AppData\Local
LOGONSERVER=\\SYAMSAIREDDY
M2_HOME=C:\apache-maven-3.6.0-bin\apache-maven-3.6.0
MAVEN_HOME=C:\apache-maven-3.6.0-bin\apache-maven-3.6.0
NUMBER_OF_PROCESSORS=8
OneDrive=C:\Users\syamp\OneDrive
OneDriveConsumer=C:\Users\syamp\OneDrive
OS=Windows_NT
Path=C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Java\jdk1.8.0_66\bin;C:\WINDOWS\System32\OpenSSH\;C:\apache-maven-3.6.0-bin\apache-maven-3.6.0\bin;C:\Program Files\Git\cmd;C:\Users\syamp\AppData\Local\Microsoft\WindowsApps;
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=8e0a
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
PUBLIC=C:\Users\Public
SESSIONNAME=Console
SystemDrive=C:
SystemRoot=C:\WINDOWS
TEMP=C:\Users\syamp\AppData\Local\Temp
TMP=C:\Users\syamp\AppData\Local\Temp
USERDOMAIN=SYAMSAIREDDY
USERDOMAIN_ROAMINGPROFILE=SYAMSAIREDDY
USERNAME=syamreddy
USERPROFILE=C:\Users\syamp
windir=C:\WINDOWS
